[server]
# The path to the Streamlit app file
mainScriptPath = "src/ui/streamlit_federal_job_app.py"

[logger]
level = "info"

[theme]
primaryColor = "#002B49"  # A professional navy blue
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"
