[server]
# The path to the Streamlit app file
mainScriptPath = "src/usajobs_skill_bridge/streamlit_federal_job_app.py"
headless = true
fileWatcherType = "poll"

[browser]
serverAddress = "0.0.0.0"
serverPort = 8501

[logger]
level = "info"

[theme]
primaryColor = "#002B49"  # A professional navy blue
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"
