[server]
headless = true
enableXsrfProtection = false
enableCORS = false

[browser]
serverAddress = "0.0.0.0"
serverPort = 8501

[logger]
level = "info"

[theme]
primaryColor = "#002B49"  # A professional navy blue
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"
